### ISSUE TITLE
Include content-length in signed headers for signed url

### ISSUE THREAD

**Issue by vasco-santos** [web3-storage/upload-api#38]
See https://github.com/web3-storage/w3up/pull/266

**Comment by olizilla** [comment]
I'm refactoring so we don't call the presigned url thing `signer` as that word is now heavily loaded. Also we have a bucket abstraction for car-store already and creating URLs for uploads to that bucket can live as part of that.

**Comment by olizilla** [comment]
Also removing the SESSION_TOKEN as it doesn't seem relevant to our use-case where we are creating the signer in a lambda with the regular aws credentials
